version: '3.9'
services:
  client:
    container_name: client
    image: client:latest
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./Client/config.ini:/config.ini
      - ./montreal:/montreal
      - ./toronto:/toronto
      - ./washington:/washington
    
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24