version: '3.9'
services:
  rabbitmq:
    build:
      context: ./Server/rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
  
  server:
    container_name: server
    image: server:latest
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq    
    networks:
      - testing_net
    environment:
      - PYTHONUNBUFFERED=1

  joiner:
    container_name: joiner
    image: joiner:latest
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    
  client:
    container_name: client
    image: client:latest
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./Client/config.ini:/config.ini
      - ./montreal:/montreal
      - ./toronto:/toronto
      - ./washington:/washington

  filter1:
    container_name: filter1
    image: filter:latest
    restart: on-failure
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - testing_net
    environment:
      - FILTER_ID=1
      - PYTHONUNBUFFERED=1


  filter2:
    container_name: filter2
    image: filter:latest
    restart: on-failure
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - testing_net
    environment:
      - FILTER_ID=2
      - PYTHONUNBUFFERED=1


  filter3:
    container_name: filter3
    image: filter:latest
    restart: on-failure
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - testing_net
    environment:
      - FILTER_ID=3
      - PYTHONUNBUFFERED=1


  filter4:
    container_name: filter4
    image: filter:latest
    restart: on-failure
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - testing_net
    environment:
      - FILTER_ID=4
      - PYTHONUNBUFFERED=1


  filter5:
    container_name: filter5
    image: filter:latest
    restart: on-failure
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - testing_net
    environment:
      - FILTER_ID=5
      - PYTHONUNBUFFERED=1


  
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

